
import SwiftUI

public struct PiCKImage {
    public static let onboardingLogo = Image("onboardingLogo", bundle: .module)
    public static let pickLogo = Image("pickLogo", bundle: .module)
    public static let adminLogo = Image("adminLogo", bundle: .module)
    public static let alert = Image("alert", bundle: .module)
    public static let bottomArrow = Image("bottomArrow", bundle: .module)
    public static let bug = Image("bug", bundle: .module)
    public static let calendar = Image("calendar", bundle: .module)
    public static let changePassword = Image("changePassword", bundle: .module)
    public static let check = Image("check", bundle: .module)
    public static let classRoomMove = Image("classRoomMove", bundle: .module)
    public static let defaultTimeTable1 = Image("defaultTimeTable1", bundle: .module)
    public static let displayMode = Image("displayMode", bundle: .module)
    public static let earlyLeave = Image("earlyLeave", bundle: .module)
    public static let eyeOff = Image("eyeOff", bundle: .module)
    public static let eyeOn = Image("eyeOn", bundle: .module)
    public static let fail = Image("fail", bundle: .module)
    public static let image = Image("image", bundle: .module)
    public static let leftArrow = Image("leftArrow", bundle: .module)
    public static let logout = Image("logout", bundle: .module)
    public static let main = Image("main", bundle: .module)
    public static let myPage = Image("myPage", bundle: .module)
    public static let navigationSetting = Image("navigationSetting", bundle: .module)
    public static let newNotice = Image("newNotice", bundle: .module)
    public static let notice = Image("notice", bundle: .module)
    public static let outing = Image("Outing", bundle: .module)
    public static let profile = Image("profile", bundle: .module)
    public static let rightArrow = Image("rightArrow", bundle: .module)
    public static let smile = Image("smile", bundle: .module)
    public static let studentIdCard = Image("studentIdCard", bundle: .module)
    public static let time = Image("time", bundle: .module)
    public static let topArrow = Image("topArrow", bundle: .module)
    public static let voice = Image("voice", bundle: .module)
    public static let weekendMeal = Image("weekendMeal", bundle: .module)
    public static let allTabIcon = Image("allTabIcon", bundle: .module)
    public static let applyIcon = Image("applyIcon", bundle: .module)
    public static let homeIcon = Image("homeIcon", bundle: .module)
    public static let scheduleIcon = Image("scheduleIcon", bundle: .module)
    public static let schoolMealIcon = Image("schoolMealIcon", bundle: .module)
}
